### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Escanor-87** [alexsvitlov/iTransmission#2]
Hi there! Thanks for nice app, works perfectly! 
Just wonder if you have plan to update core and app itself? I mean, new features, new look maybe?

**Comment by alexsvitlov** [comment]
Hi @Escanor-87 , really appreciate the kind words.
The priority is update the Core for now. Don't have much capacity to work on the UI right now.

**Comment by Escanor-87** [comment]
Glad to hear that you are working on it! 
Don't leave this project, please, it's the best one out there.
Thanks for your time and hard work 💪
